college/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kec/', include('kec.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kec/urls.py
from django.urls import path
from . import views
from .api import AppView, DepartmentView, StaffView
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'kec'
urlpatterns = [
    path('', views.index, name='index'),
    path('application/', views.application, name='application'),
    path('stu_registration/', views.student_registration, name='stu-register'),
    path('staff_register/', views.staff_registration, name='staff-register'),
    path('student_login/', views.student_login, name='student_login'),
    path('staff_login/', views.staff_login, name='staff_login'),
    path('student_details/', views.student_details, name='student_details'),
    path('staff_details/', views.staff_details, name='staff_details'),
    path('staff_list/', views.staff_list, name='staff_list'),
    path('student_list/', views.student_list, name='student_list'),
    path('staff/', views.staff, name='staff'),
    path('students/', views.student, name='student'),
    path('apply/', AppView.as_view()),
    path('department/', DepartmentView.as_view()),
    path("staff_api/", StaffView.as_view()),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth')
]
urlpatterns = format_suffix_patterns(urlpatterns) 

kec/models.py
from django.db import models
from django.contrib.auth.models import User


class StudentApplication(models.Model):
    student_name = models.CharField(max_length=50)
    email = models.CharField(max_length=20)
    ssc_percentage= models.CharField(max_length=10)
    inter_percentage= models.CharField(max_length=10)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email


class Department(models.Model):
    department_name= models.CharField(max_length=30)

    def __str__(self):
        return self.department_name


class Student(models.Model):
    student_application = models.OneToOneField(StudentApplication, on_delete=models.CASCADE, null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_name = models.CharField(max_length=50)
    dob = models.DateField()
    father_name = models.CharField(max_length=50)
    mother_name = models.CharField(max_length=50)
    mobile_no = models.CharField(max_length=10)
    ssc_percentage = models.CharField(max_length=10)
    inter_percentage = models.CharField(max_length=10)
    student_image = models.ImageField(upload_to='images/')
    gender = models.CharField(max_length=10)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)


class Staff(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    staff_name = models.CharField(max_length=50)
    mobile_no = models.CharField(max_length=10)
    experience = models.CharField(max_length=12)
    specialization = models.CharField(max_length=20)
    gender = models.CharField(max_length=10)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    staff_image = models.ImageField(upload_to='images/', null=True, blank=True)

kec/forms.py
from django.forms import ModelForm
from .models import StudentApplication, Student, Staff
from django.contrib.auth.models import User


class StudentApplicationForm(ModelForm):

    class Meta:
        model = StudentApplication
        fields = '__all__'
        exclude = ['is_verified']


class UserCreationForm(ModelForm):

    class Meta:
        model = User
        fields = '__all__'
        exclude = ['first_name', 'last_name']


class StudentForm(ModelForm):

    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['ssc_percentage', 'inter_percentage']


class StaffForm(ModelForm):

    class Meta:
        model = Staff
        fields = '__all__'

kec/views.py
from django.shortcuts import render
from .models import StudentApplication, Department, Student, Staff
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .forms import StudentApplicationForm, UserCreationForm, StaffForm



def index(request):
    return render(request, 'kec/index.html')


def application(request):
    if request.method == 'POST':
        application_form = StudentApplicationForm(request.POST)
        if application_form.is_valid():
            application_form.save()
            return HttpResponseRedirect('/kec/')

        # StudentApplication.objects.create(
        #     student_name=request.POST['student_name'],
        #     email=request.POST['email'],
        #     ssc_percentage=request.POST['ssc_percentage'],
        #     inter_percentage=request.POST['inter_percentage'])
        # return HttpResponseRedirect('/kec/')
    # return render(request, 'kec/application.html')
    else:
        application_form = StudentApplicationForm()
    return render(request, 'kec/application.html', {'form': application_form})


def student_registration(request):
    if request.method == 'POST':
        student = StudentApplication.objects.filter(email=request.POST['email'], is_verified=True)
        if not student.exists():
            return render(request, "kec/application.html", {"error": "Apply and Register."})
        user = User.objects.create_user(
            username=request.POST['username'],
            password=request.POST['password'],
            email=request.POST['email']
        )
        department = Department.objects.get(department_name =request.POST['department'])
        Student.objects.create(
            student_name=request.POST['student_name'],
            dob=request.POST['dob'],
            father_name=request.POST['father_name'],
            mother_name=request.POST['mother_name'],
            mobile_no=request.POST['mobile_no'],
            gender=request.POST['gender'],
            student_image=request.FILES['student_image'],
            student_application=student.first(),
            department=department,
            user=user
        )
        return HttpResponseRedirect('/kec/')
    return render(request, 'kec/student_registration.html')


def staff_registration(request):
    if request.method == 'POST':
        user_form = UserCreationForm(request.POST)
        staff_form = StaffForm(request.POST and request.FILES)
        form = user_form and staff_form
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/kec/')

    #     user = User.objects.create_user(
    #         username=request.POST['username'],
    #         password=request.POST['password'],
    #         email=request.POST['email']
    #     )
    #     department = Department.objects.get(department_name=request.POST['department'])
    #     Staff.objects.create(
    #         staff_name=request.POST['staff_name'],
    #         mobile_no=request.POST['mobile_no'],
    #         experience=request.POST['experience'],
    #         specialization=request.POST['specialization'],
    #         gender=request.POST['gender'],
    #         department=department,
    #         staff_image=request.FILES['staff_image'],
    #         user=user
    #     )
    #     return HttpResponseRedirect('/kec/')
    # return render(request, 'kec/staff_register.html')
    else:
        form = UserCreationForm and StaffForm
    return render(request, 'kec/staff_register.html', {'form': form})


def student_login(request):
    if request.method == 'POST':
        user = authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/kec/student_details/')
        else:
            return render(request, 'kec/student_login.html', {'error_message': 'Invalid Credentials'})
    return render(request, 'kec/student_login.html')


def staff_login(request):
    if request.method == 'POST':
        user = authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/kec/staff_details')
        else:
            return render(request, 'kec/staff_login.html', {'error_message': 'Invalid Credentials'})
    return render(request, 'kec/staff_login.html')


def student_details(request):
    student = request.user.student
    return render(request, 'kec/student_details.html', {'student': student})


def staff_details(request):
    staff = request.user.staff
    return render(request, 'kec/staff_details.html', {'staff': staff})


def staff_list(request):
    staf_list = Staff.objects.filter(department= request.user.student.department)
    return render(request, 'kec/staff_list.html', {'staf_list': staf_list})


def student_list(request):
    stu_list = Student.objects.filter(department=request.user.staff.department)
    return render(request, 'kec/student_list.html', {'stu_list': stu_list})


def staff(request):
    sta = Staff.objects.order_by('id')
    return render(request, 'kec/staff.html', {'sta': sta})


def student(request):
    stu = Student.objects.order_by('-department_id')
    return render(request, 'kec/student.html', {'stu': stu})

kec/templates/kec/application.html
{% if error %}
<h3>{{error}}</h3>
{% endif %}
<h2>Application Form</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
<!--    Student-Name : <input name="student_name" type="text"><br>-->
<!--    Email : <input name="email" type="email"><br>-->
<!--    SSC_Percentage : <input name="ssc_percentage" type="text"><br>-->
<!--    Inter_Percentage : <input name="inter_percentage" type="text"><br>-->
    <input type="submit" value="SAVE">
</form><br><br>
<a href="">Back</a>

kec/templates/kec/index.html
<h1>Welcome To KEC</h1>

<a href="{% url 'kec:application' %}">Student Application>>></a><br><br>
<a href="{% url 'kec:stu-register' %}">Student Registration>>></a><br><br>
<a href="{% url 'kec:staff-register' %}">Staff Registration>>></a><br><br>
<a href="{% url 'kec:student_login' %}">Student Login>>> </a><br><br>
<a href="{% url 'kec:staff_login' %}">Staff Login>>></a>

kec/templates/kec/staff.html
{% if sta %}
<ul>
    {% for s in sta %}
        <li>{{ s.staff_name }}--{{ s.department }}</li>
    {% endfor %}
</ul>
{% endif %}

<br><br><br>
<a href="{% url 'kec:index' %}">HOME</a>

kec/templates/kec/staff_details.html
Name   : {{ staff.staff_name }}<br>
Email : {{ user.email }}<br>
Gender : {{ staff.gender }}<br>
Mobile-No : {{ staff.mobile_no}}<br>
Specialization : {{ staff.specialization }}<br>
Experience : {{ staff.experience }}<br>
Department : {{ staff.department }}<br>
Image : <br><img src="/media/{{ staff.staff_image }}" alt="No image" width="300" height="150">
<br><br><br>
<a href="{% url 'kec:student_list' %}"> Department-Students</a>|||||<a href="{% url 'kec:student' %}">All-Students</a>

<br><br><br>
<a href="{% url 'kec:index' %}">HOME</a>

kec/templates/kec/staff_list.html
{% if staf_list%}
<ul>
    {% for each in staf_list%}
        <li>{{each.staff_name}}--{{each.specialization}}</li>
    {% endfor %}
</ul>
{% else %}
    No staff available
{% endif %}

br><br><br>
<a href="{% url 'kec:index' %}">HOME</a>

kec/templates/kec/staff_login.html
<!--{% if error %}-->
<!--    <h1> {{error}}</h1>-->
<!--{% endif %}-->
<form action="" method="post">
    {% csrf_token %}
    Username : <input name="username" type="text"><br>
    Password : <input name="password" type="password"><br>
    <input type="submit" value="Login">
</form>

kec/templates/kec/staff_register.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
<!--    Username : <input name="username" type="text"><br>-->
<!--    Password : <input name="password" type="password"><br>-->
<!--    Email : <input name="email" type="email"><br>-->
<!--    Staff_Name : <input name="staff_name" type="text"><br>-->
<!--    Specialization : <input name="specialization" type="text"><br>-->
<!--    Experience : <input name="experience" type="text"><br>-->
<!--    Mobile-No : <input name="mobile_no" type="text"><br>-->
<!--    Gender : <input name="gender" type="text"><br>-->
<!--    Staff-Image : <input name="staff_image" type="file"><button type="submit">Upload</button><br>-->
<!--    Department :-->
<!--    <select name="department">-->
<!--        <option value="Mechanical">Mechanical</option>-->
<!--        <option value="Electrical">Electrical</option>-->
<!--        <option value="Electronics">Electronics</option>-->
<!--        <option value="Civil">Civil</option>-->
<!--        <option value="Computer Science">Computer Science</option>-->
    </select><br>
    <input type="submit" value="SAVE">

</form>
<br><br><br>
<a href="{% url 'kec:index' %}">BACK</a>

kec/templates/kec/student.html
{% if stu %}
<ul>
    {% for s in stu %}
        <li>{{ s.student_name }}--{{ s.department }}</li>
    {% endfor %}
</ul>
{% endif %}
<br><br><br>
<a href="{% url 'kec:index' %}">HOME</a>

kec/templates/kec/student_details.html
{% if student %}
Name   : {{ student.student_name }}<br>
Email : {{ user.email }}<br>
DOB    : {{ student.dob }}<br>
Gender : {{ student.gender }}<br>
Mobile-No : {{ student.mobile_no}}<br>
Father's Name : {{ student.father_name }}<br>
Mothers Name : {{ student.mother_name }}<br>
Department : {{ student.department }}<br>
Image : <br><img src="/media/{{ student.student_image }}" alt="No image" width="300" height="150">
{% else %}
No Students are available
{% endif %}
<br><br><br>
<a href="{% url 'kec:staff_list' %}">Department-Staff</a>|||||<a href="{% url 'kec:staff' %}">All-Staff</a>
<br><br><br>
<a href="{% url 'kec:index' %}">HOME</a>

kec/templates/kec/student_list.html
{% if stu_list %}
<ul>
    {% for ea in stu_list%}
            <li>{{ea.student_name}}</li>
    {% endfor %}
</ul>
{% else %}
    No Students are available
{% endif %}

<br><br><br>
<a href="{& url 'kec:index' %}">HOME</a>

kec/templates/kec/student_login.html
{% if error_message %}
    {{ error_message }}
{% else %}
<form action="" method="post">
    {% csrf_token %}
    Username : <input name="username" type="text"><br>
    Password : <input name="password" type="password"><br>
    <input type="submit" value="Login">
</form>
{% endif %}

kec/templates/kec/student_registration.html
<h1> Student-Registration Form</h1>
{% if error_message %}
    {{ error_message }}
{% else %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    Username : <input name="username" type="text"><br>
    Password : <input name="password" type="password"><br>
    Email : <input name="email" type="email"><br>
    Student_Name : <input name="student_name" type="text"><br>
    Date of Birth : <input name="dob" type="date"><br>
    Father's Name : <input name="father_name" type="text"><br>
    Mother's Name : <input name="mother_name" type="text"><br>
    Mobile-No : <input name="mobile_no" type="text"><br>
    Gender : <input name="gender" type="text"><br>
    Student-Image : <input name="student_image" type="file"><button type="submit">Upload</button><br>
    Department :
    <select name="department">
        <option value="Mechanical">Mechanical</option>
        <option value="Electrical">Electrical</option>
        <option value="Electronics">Electronics</option>
        <option value="Civil">Civil</option>
        <option value="Computer Science">Computer Science</option>
    </select><br>
    <input type="submit" value="SAVE">

</form>
{% endif %}
<br><br><br>
<a href="{% url 'kec:index' %}">BACK</a>